on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: "go.mod"
      - name: Install dependencies
        run: sudo apt-get install -y libxml2-dev pkg-config
      - name: Run tests
        id: run-tests
        run: make go-test
