<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="customer" type="xs:string"/>
				<xs:element name="items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="quantity" type="xs:int"/>
										<xs:element name="sku" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
